package com.aws.dynamodb_springboot.model;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

@DynamoDBTable(tableName = "employee")
@Data
@AllArgsConstructor
@NoArgsConstructor
public class Employee {

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private String employeeId;

    @DynamoDBRangeKey
    private String departmentId;

    @DynamoDBAttribute
    private String name;

    @DynamoDBAttribute
    private String role;
}
